# Generated by Django 5.2.13 on 2026-05-06 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("restock", "Пополнение"),
                            ("count", "Инвентаризация"),
                            ("damage", "Списание брака"),
                            ("return", "Возврат на склад"),
                            ("manual", "Ручная корректировка"),
                        ],
                        max_length=24,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("previous_quantity", models.PositiveIntegerField()),
                ("new_quantity", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_adjustments",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["variant", "created_at"],
                        name="catalog_inv_variant_a5f6d3_idx",
                    ),
                    models.Index(
                        fields=["reason"], name="catalog_inv_reason_3db8dd_idx"
                    ),
                ],
            },
        ),
    ]
