# Generated by Django 5.2.13 on 2026-05-25 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productimage_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommendation_body_shape_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_fit_confidence',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_fit_tendency',
            field=models.CharField(choices=[('true_to_size', 'Соответствует размеру'), ('runs_small', 'Маломерит'), ('runs_large', 'Большемерит'), ('oversized_design', 'Оверсайз по дизайну')], default='true_to_size', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_layering_role',
            field=models.CharField(blank=True, choices=[('base', 'База'), ('mid', 'Средний слой'), ('outer', 'Верхний слой'), ('statement', 'Акцент')], max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_seasonality',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_silhouette',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_style_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='recommendation_fit_tendency_override',
            field=models.CharField(blank=True, choices=[('true_to_size', 'Соответствует размеру'), ('runs_small', 'Маломерит'), ('runs_large', 'Большемерит'), ('oversized_design', 'Оверсайз по дизайну')], max_length=24),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='recommendation_notes_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='RecommendationDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('product_detail', 'Карточка товара'), ('product_list', 'Список товаров'), ('recommendation_api', 'Recommendation API'), ('checkout', 'Checkout snapshot')], max_length=32)),
                ('recommended_size', models.CharField(blank=True, max_length=16)),
                ('confidence', models.CharField(blank=True, max_length=16)),
                ('risk_level', models.CharField(blank=True, max_length=16)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('fallback_action', models.CharField(blank=True, max_length=120)),
                ('profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source', 'created_at'], name='catalog_reco_source_idx'), models.Index(fields=['product', 'created_at'], name='catalog_reco_product_idx')],
            },
        ),
    ]
