# Generated by Django 5.2.13 on 2026-04-22 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_created", "Заказ создан"),
                            ("order_status", "Статус заказа"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email")], default="email", max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("delivered", "Доставлено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("error_message", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "notification_type"],
                        name="notifications_order_type_idx",
                    ),
                    models.Index(fields=["status"], name="notifications_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "notification_type", "channel"),
                        name="unique_notification_per_order_type_channel",
                    )
                ],
            },
        ),
    ]
