# Generated by Django 5.2.13 on 2026-04-22 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("delivered", "Доставлено"), ("failed", "Ошибка")],
                        max_length=16,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=160)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="notifications.notificationlog",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["notification", "created_at"],
                        name="notif_attempt_log_idx",
                    ),
                    models.Index(fields=["status"], name="notif_attempt_status_idx"),
                ],
            },
        ),
    ]
