# Generated by Django 5.2.13 on 2026-05-19 22:52

import django.db.models.deletion
from django.db import migrations, models


MIGRATION_SAFETY_PLAN = {
    "ticket": "OPS-000",
    "summary": "Replace conditional unique constraint with dedupe_key index/uniqueness for notification logs.",
    "backfill": "No backfill required for existing rows; new constraints allow empty dedupe_key and preserve previous conditional uniqueness for order/type/channel.",
    "deploy_strategy": "Deploy code that writes dedupe_key (when applicable) before applying this migration to avoid race conditions during constraint swap.",
    "rollback": "Rollback application code first; then revert migration which restores previous constraints (dedupe_key column remains but is non-breaking).",
}


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notificationlog_processing_started_at_and_more"),
        ("orders", "0007_order_coupon_order_currency_order_delivery_amount_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationlog",
            name="unique_notification_per_order_type_channel",
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Заказ создан"),
                    ("order_status", "Статус заказа"),
                    ("payment_status", "Статус оплаты"),
                    ("shipping_status", "Статус доставки"),
                    ("low_stock", "Низкий остаток"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["dedupe_key"], name="notifications_dedupe_key_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order", None), _negated=True),
                fields=("order", "notification_type", "channel"),
                name="unique_notification_per_order_type_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedupe_key", ""), _negated=True),
                fields=("dedupe_key",),
                name="unique_notification_dedupe_key",
            ),
        ),
    ]
