# Generated by Django 5.2.13 on 2026-04-22 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["idempotency_key"], name="orders_idempo_key_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("user", "idempotency_key"),
                name="unique_order_idempotency_per_user",
            ),
        ),
    ]
