# Generated by Django 5.2.13 on 2026-05-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_idempotency_key_order_orders_idempo_key_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("picking", "На сборке"),
                    ("packed", "Упакован"),
                    ("shipped", "Передан в доставку"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                    ("returned", "Возвращён"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
    ]
