# Generated by Django 5.2.13 on 2026-05-06 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="priority",
            field=models.CharField(
                choices=[
                    ("normal", "Обычный"),
                    ("high", "Приоритетный"),
                    ("urgent", "Срочный"),
                ],
                default="normal",
                max_length=16,
            ),
        ),
    ]
