# Generated by Django 5.2.13 on 2026-05-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_coupon_order_currency_order_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recommendation_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
