# Generated by Django 5.2.13 on 2026-04-21 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("courier", "Курьер"),
                            ("pickup", "Самовывоз"),
                            ("post", "Почта"),
                        ],
                        default="courier",
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "estimated_days_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_days_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("requires_address", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="delivery_me_active_0e0e1c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderDeliverySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_code", models.CharField(max_length=48)),
                ("method_name", models.CharField(max_length=120)),
                (
                    "method_kind",
                    models.CharField(
                        choices=[
                            ("courier", "Курьер"),
                            ("pickup", "Самовывоз"),
                            ("post", "Почта"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "estimated_days_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_days_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("recipient_name", models.CharField(max_length=160)),
                ("recipient_phone", models.CharField(max_length=32)),
                ("country", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=120)),
                ("postal_code", models.CharField(max_length=32)),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_snapshots",
                        to="delivery.deliverymethod",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_snapshot",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["method_code"], name="delivery_or_method_2bb933_idx"
                    )
                ],
            },
        ),
    ]
