# Generated by Django 5.2.13 on 2026-05-04 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Ожидает передачи"),
                            ("handed_over", "Передан в службу доставки"),
                            ("in_transit", "В пути"),
                            ("out_for_delivery", "Курьер уже едет"),
                            ("delivered", "Доставлен"),
                            ("failed", "Проблема с доставкой"),
                            ("returned", "Возвращается отправителю"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает передачи"),
                            ("handed_over", "Передан в службу доставки"),
                            ("in_transit", "В пути"),
                            ("out_for_delivery", "Курьер уже едет"),
                            ("delivered", "Доставлен"),
                            ("failed", "Проблема с доставкой"),
                            ("returned", "Возвращается отправителю"),
                        ],
                        max_length=24,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("external_event_id", models.CharField(blank=True, max_length=120)),
                ("happened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="orderdeliverysnapshot",
            name="current_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="orderdeliverysnapshot",
            name="external_shipment_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="orderdeliverysnapshot",
            name="last_tracking_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderdeliverysnapshot",
            name="provider_code",
            field=models.SlugField(default="manual", max_length=48),
        ),
        migrations.AddField(
            model_name="orderdeliverysnapshot",
            name="tracking_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает передачи"),
                    ("handed_over", "Передан в службу доставки"),
                    ("in_transit", "В пути"),
                    ("out_for_delivery", "Курьер уже едет"),
                    ("delivered", "Доставлен"),
                    ("failed", "Проблема с доставкой"),
                    ("returned", "Возвращается отправителю"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="orderdeliverysnapshot",
            index=models.Index(
                fields=["tracking_status"], name="delivery_or_tracki_2a5973_idx"
            ),
        ),
        migrations.AddField(
            model_name="deliverytrackingevent",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_events",
                to="delivery.orderdeliverysnapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytrackingevent",
            index=models.Index(
                fields=["snapshot", "created_at"], name="delivery_tr_snapsh_3ce87a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytrackingevent",
            index=models.Index(
                fields=["external_event_id"], name="delivery_tr_extern_1e9cb0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverytrackingevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_event_id", ""), _negated=True),
                fields=("snapshot", "external_event_id"),
                name="unique_delivery_tracking_external_id",
            ),
        ),
    ]
