# Generated by Django 5.2.13 on 2026-05-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_deliverytrackingevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverytrackingevent",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает передачи"),
                    ("created", "Оформлена накладная"),
                    ("handed_over", "Передан в службу доставки"),
                    ("in_transit", "В пути"),
                    ("out_for_delivery", "Курьер уже едет"),
                    ("delivered", "Доставлен"),
                    ("failed", "Проблема с доставкой"),
                    ("returned", "Возвращается отправителю"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="deliverytrackingevent",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Ожидает передачи"),
                    ("created", "Оформлена накладная"),
                    ("handed_over", "Передан в службу доставки"),
                    ("in_transit", "В пути"),
                    ("out_for_delivery", "Курьер уже едет"),
                    ("delivered", "Доставлен"),
                    ("failed", "Проблема с доставкой"),
                    ("returned", "Возвращается отправителю"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="orderdeliverysnapshot",
            name="tracking_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает передачи"),
                    ("created", "Оформлена накладная"),
                    ("handed_over", "Передан в службу доставки"),
                    ("in_transit", "В пути"),
                    ("out_for_delivery", "Курьер уже едет"),
                    ("delivered", "Доставлен"),
                    ("failed", "Проблема с доставкой"),
                    ("returned", "Возвращается отправителю"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
    ]
