# Generated by Django 5.2.13 on 2026-05-19 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_indexes_for_admin_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('kind', models.CharField(choices=[('fixed', 'Fixed discount'), ('percent', 'Percent discount'), ('free_shipping', 'Free shipping')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percent', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('min_cart_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('max_redemptions', models.PositiveIntegerField(default=0)),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='pricing_coupon_active_idx'), models.Index(fields=['code'], name='pricing_coupon_code_idx')],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['code'], name='pricing_gift_code_idx'), models.Index(fields=['expires_at'], name='pricing_gift_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='GiftCardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='pricing.giftcard')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_redemptions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='pricing.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['coupon', 'user', 'created_at'], name='pricing_coupon_user_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order', None), _negated=True), fields=('coupon', 'order'), name='unique_coupon_redemption_per_order')],
            },
        ),
    ]
