# Generated by Django 5.2.13 on 2026-04-21 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("provider_code", models.SlugField(default="manual", max_length=48)),
                (
                    "session_mode",
                    models.CharField(
                        choices=[
                            ("none", "Без сессии"),
                            ("placeholder", "Локальная сессия"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="payments_me_active_1d802d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_code", models.CharField(max_length=48)),
                ("provider_code", models.SlugField(default="manual", max_length=48)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("session_created", "Сессия создана"),
                            ("authorized", "Средства авторизованы"),
                            ("succeeded", "Оплачен"),
                            ("failed", "Ошибка оплаты"),
                            ("cancelled", "Отменен"),
                            ("refunded", "Возвращен"),
                            ("expired", "Истек"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="RUB", max_length=3)),
                ("external_payment_id", models.CharField(blank=True, max_length=120)),
                ("idempotency_key", models.CharField(blank=True, max_length=120)),
                ("session_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("session_created", "Сессия создана"),
                            ("authorized", "Средства авторизованы"),
                            ("succeeded", "Оплачен"),
                            ("failed", "Ошибка оплаты"),
                            ("cancelled", "Отменен"),
                            ("refunded", "Возвращен"),
                            ("expired", "Истек"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("session_created", "Сессия создана"),
                            ("authorized", "Средства авторизованы"),
                            ("succeeded", "Оплачен"),
                            ("failed", "Ошибка оплаты"),
                            ("cancelled", "Отменен"),
                            ("refunded", "Возвращен"),
                            ("expired", "Истек"),
                        ],
                        max_length=24,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("external_event_id", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["payment", "created_at"],
                        name="payments_ev_payment_2791bc_idx",
                    ),
                    models.Index(
                        fields=["external_event_id"],
                        name="payments_ev_externa_69f741_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="payments_pa_order_6c0b5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_6b742b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["idempotency_key"], name="payments_pa_idempo_7b4d67_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("user", "idempotency_key"),
                name="unique_payment_idempotency_per_user",
            ),
        ),
    ]
