# Generated by Django 5.2.13 on 2026-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('payment', 'external_event_id'), name='unique_payment_event_external_id'),
        ),
    ]
