# Generated by Django 5.2.13 on 2026-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentevent_unique_payment_event_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="session_mode",
            field=models.CharField(
                choices=[
                    ("none", "Без сессии"),
                    ("placeholder", "Локальная сессия"),
                    ("redirect", "Hosted checkout / redirect"),
                ],
                default="none",
                max_length=24,
            ),
        ),
    ]
