# Generated by Django 5.2.13 on 2026-04-22 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("order", "Вопрос по заказу"),
                            ("delivery", "Доставка"),
                            ("return", "Возврат или обмен"),
                            ("product", "Товар или размер"),
                            ("partnership", "Партнерство"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("order_number", models.CharField(blank=True, max_length=32)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("in_progress", "В работе"),
                            ("resolved", "Решено"),
                            ("spam", "Спам"),
                        ],
                        default="new",
                        max_length=24,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="support_status_idx"
                    ),
                    models.Index(
                        fields=["email", "created_at"], name="support_email_idx"
                    ),
                ],
            },
        ),
    ]
