# Generated by Django 5.2.14 on 2026-05-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_phone_verified_at_phoneconfirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fit_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="fit_profile_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
