# Generated by Django 5.2.13 on 2026-05-08 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("change", "Change"),
                            ("delete", "Delete"),
                            ("admin_action", "Admin action"),
                        ],
                        max_length=32,
                    ),
                ),
                ("app_label", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("object_id", models.CharField(max_length=128)),
                ("object_repr", models.CharField(max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("request_path", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"], name="audit_action_created_idx"
                    ),
                    models.Index(
                        fields=["app_label", "model", "object_id"],
                        name="audit_target_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="audit_actor_created_idx"
                    ),
                ],
            },
        ),
    ]
